@startuml
artifact artifact0  as "spring-petclinic (Original)"

artifact artifact1  as "spring-petclinic-3tier"
artifact artifact2  as "spring-petclinic-3tier-2"
artifact artifact3  as "spring-petclinic-3tier-3"
artifact artifact4  as "spring-petclinic-3tier-4"
artifact artifact5  as "spring-petclinic-ddd"
artifact artifact34 as "spring-petclinic-ddd-9m"

artifact artifact21 as "spring-petclinic-hex"

artifact artifact31 as "spring-petclinic-hex-ddd"
artifact artifact32 as "spring-petclinic-hex-ddd-cqrs"
artifact artifact33 as "spring-petclinic-hex-ddd-eda"

artifact0 --> artifact1: baseline

artifact1 --> artifact21: hexagonal architeture
artifact1 --> artifact2: separate web model \n(separate input concern)
artifact2 -right[hidden]-> artifact21
artifact2 --> artifact3: separate persistence model \n(separate output concern)
artifact3 --> artifact4: invert persistence operations \n(invert output dependency)
artifact4 --> artifact5: invert application operations \n(invert input dependency)

artifact5 --> artifact34

artifact5 --> artifact31
artifact21 --> artifact31
artifact31 --> artifact32
artifact31 --> artifact33

@enduml